### PR TITLE
scripts added for cep-testbed image.

### PR DESCRIPTION
**Pull request by geonexus**
### REVIEWERS

@flopezag 
### DESCRIPTION
- scripts added for cep-testbed image.

### CODE REVIEW

**Comment by jframos** [comment]
I do not know if this is a proper way but we thought that it is better to put the release number (FIWARE release?) in the name of the script files, in order to have all scripts of all releases in the directory:

```
                  fiware-enablers
                    ├───README.rst
                    ├───images
                    │   ├───README.rst
                    │   ├───<GEri/GEi-name1>
                    │   │   ├───4.4_create.sh
                    |   |   ├───4.4_test.sh
                    │   │   ├───5.1_create.sh
                    │   │   ├───5.1_test.sh
                    │   │   └───...
```

**Comment by geonexus** [comment]
Which is the current release?
Some scripts provide a version, but this GEri do not.

**Comment by jframos** [comment]
Current release is **5.1**, but are they referred to this release? or to the previous one? @flopezag

**Comment by flopezag** [comment]
I assume that the scripts that we are uploading corresponding to the R4.4

**Comment by jframos** [comment]
LGTM

**Comment by flopezag** [comment]
LGTM

**Pull request merged**
